# This is for Development users namespace
apiVerison: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
# This is for Qulaity Test users namespace
apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    name: qa
---
# This is for Producation team users namespace
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
